// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: student.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const registerStudent = `-- name: RegisterStudent :one
INSERT INTO students(id, created_at, updated_at, name,subject,class,fees,fee_status)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, created_at, updated_at, name, subject, class, fees, fee_status
`

type RegisterStudentParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Subject   string
	Class     string
	Fees      int32
	FeeStatus string
}

func (q *Queries) RegisterStudent(ctx context.Context, arg RegisterStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, registerStudent,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Subject,
		arg.Class,
		arg.Fees,
		arg.FeeStatus,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Subject,
		&i.Class,
		&i.Fees,
		&i.FeeStatus,
	)
	return i, err
}
